name: loom_frontend
description: "Loom Headless Media Server Client App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  media_kit: ^1.2.6
  media_kit_libs_video: ^1.0.7
  media_kit_video: ^2.0.1
  shared_preferences: ^2.2.3
  universal_html: ^2.3.0
  window_manager: ^0.3.9
  table_calendar: ^3.1.2
  intl: ^0.20.0
  file_picker: ^8.0.0
  url_launcher: ^6.3.2
  just_audio: ^0.10.5
  audio_session: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
